### ISSUE TITLE
how to set the PinEntryEditText get focus when activity start

### ISSUE THREAD

**Issue by ciferLiao** [alphamu/PinEntryEditText#10]

**Comment by Joe-Mobarak-WoLf** [comment]
you can call this method guys and give it the view you want 

public static void showKeyboard(View view) {
        if (view != null) {
            InputMethodManager imm = (InputMethodManager) view.getContext().getSystemService(Context.INPUT_METHOD_SERVICE);
            imm.toggleSoftInput(InputMethodManager.SHOW_FORCED, 0);
        }
    }
