### ISSUE TITLE
setError Method not working outside "onPinEntered" method

### ISSUE THREAD

**Issue by Ramkesh9** [alphamu/PinEntryEditText#22]
i want to setError feature when an button is clicked , but this is not working. 
Actually editext ui is not updating with red . its not updating at real time (Automatically) , its updating when i do touch on edit text manually.

MyFlow :-
i am getting response from server for whether pin is valid is not , but when i am using et.setError after network call validation failed, then it is not working .
mean while it's only working inside this not outside.
pinEntry2.setOnPinEnteredListener(new PinEntryEditText.OnPinEnteredListener() {
                @Override
                public void onPinEntered(CharSequence str) {
                    if (str.toString().equals("1234")) {
                        Toast.makeText(MainActivity.this, "SUCCESS", Toast.LENGTH_SHORT).show();
                    } else {
                        pinEntry2.setError(true);
                        Toast.makeText(MainActivity.this, "FAIL", Toast.LENGTH_SHORT).show();
                        pinEntry2.postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                pinEntry2.setText(null);
                            }
                        }, 1000);
                    }
                }
            });

Give me any solution.

**Comment by alphamu** [comment]
forgot to call `invalidate()` in `setError()` should be fixed in the next release.
