### ISSUE TITLE
background will not go squared

### ISSUE THREAD

**Issue by Raykud** [alphamu/PinEntryEditText#25]
@alphamu I tried to replicate something like this: 
![screen shot 2018-01-29 at 5 51 43 pm](https://user-images.githubusercontent.com/4366666/35540772-19908538-051d-11e8-8b07-9e47648913b1.png)
however no matter if I try with the drawable exported as: 
![celular_imput_img](https://user-images.githubusercontent.com/4366666/35540791-333bd8ac-051d-11e8-8a33-5050991fb9d9.png)
or as XML:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <size
        android:width="69dp"
        android:height="69dp" />
    <corners android:radius="8dp" />
    <solid android:color="@color/white" />

</shape>
```
either with or without size it will always show like this:
<img width="326" alt="screen shot 2018-01-29 at 5 54 40 pm" src="https://user-images.githubusercontent.com/4366666/35540841-82006b56-051d-11e8-9ed2-294cf0f264c3.png">
like cropped/squashed.

Here is how I tried: 

```
<com.alimuzaffar.lib.pin.PinEntryEditText
        android:id="@+id/et_validation_code"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginEnd="20dp"
        android:layout_marginStart="20dp"
        android:layout_marginTop="30dp"
        android:cursorVisible="false"
        android:digits="1234567890"
        android:inputType="number"
        android:maxLength="4"
        android:textColor="@color/text_color_default"
        android:textIsSelectable="false"
        android:textSize="25sp"
        app:pinAnimationType="none"
        app:pinBackgroundDrawable="@drawable/celular_imput_img"
        app:pinCharacterSpacing="4dp" />
```

and using` app:pinBackgroundIsSquare="true"` is not an option as it will get even worse (small and not properly aligned).

<img width="324" alt="screen shot 2018-01-29 at 6 00 23 pm" src="https://user-images.githubusercontent.com/4366666/35541026-60c23ebe-051e-11e8-94be-40169c837746.png">

**Comment by alphamu** [comment]
This should be fixed in 2.0.5 (coming soon).
