### ISSUE TITLE
not able to import the library in android studio

### ISSUE THREAD

**Issue by raaf003** [alphamu/PinEntryEditText#28]
Error:(35, 13) Failed to resolve: com.alimuzaffar.lib:pinentryedittext:1.3.2

**Comment by eltos** [comment]
There is no version 1.3.2 yet, try 1.3.1 instead: https://jitpack.io/#alphamu/PinEntryEditText

**Comment by raaf003** [comment]
Yes I did the same ....readme should be updated with the correct version

**Comment by eltos** [comment]
Actually, there is v1.3.3 (see #27)
