### ISSUE TITLE
Set Pin Length.

### ISSUE THREAD

**Issue by derrysd** [alphamu/PinEntryEditText#3]
Hello Ali, this is a cool library. But, however I want to change the maxLength dynamically on my activities.

**Comment by sahildave** [comment]
Hey I am using this library in one of my project. I have forked and written a method for doing this:

```
    public void setMaxLength(final int maxLength) {
        mMaxLength = maxLength;
        mNumChars = maxLength;
    }
```

I can create a pull request if needed.

**Comment by alphamu** [comment]
@sahildave if you make a PR I'm happy to merge it.

**Comment by kevalpatel2106** [comment]
@alphamu @sahildave @derrysd I generated the pull request #6 for fixing of this issue.

**Comment by randiw** [comment]
my approach for this

```java
    public void setMaxLength(int length) {
        mMaxLength = length;
        mNumChars = mMaxLength;
        setFilters(new InputFilter[]{new InputFilter.LengthFilter(mMaxLength)});
        calculateSize();
        invalidate();
    }
```

you need to add calculateSize()` to adjust the character width according to given space

**Comment by rzhik** [comment]
I see that setMaxLength method was added, but it is not available in version 1.3.1. When new release will be available?

**Comment by alphamu** [comment]
The latest coffee should be deployed, I'll double check and get back to you.

**Comment by alphamu** [comment]
You were right, the latest code was not deployed. please check `v1.3.3` it should be there.
