### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by datbreau** [alphamu/PinEntryEditText#31]
I have been trying to use this library and after adding adding dependency and syncing gradle , all i get is failed to resolve: com.alimuzaffar.lib:pinentryedittext:1.3.2.

Please help

**Comment by stevyhacker** [comment]
PinEntryEditText README.md should be updated, seems like a wrong version is used, 1.3.1 is correct.

**Comment by alphamu** [comment]
Closing, let me know if the issue is still there

**Comment by saeedmashhadi** [comment]
Facing the same issue in version 1.3.1. I also changed version to 1.3.3 but didn't work
