### ISSUE TITLE
Failed to resolve: com.alimuzaffar.lib:pinentryedittext:1.3.2

### ISSUE THREAD

**Issue by palratnesh05** [alphamu/PinEntryEditText#43]
Failed to resolve: com.alimuzaffar.lib:pinentryedittext:1.3.2

**Comment by paulVulog** [comment]
No version 1.3.2. Use 1.3.3 instead
https://github.com/alphamu/PinEntryEditText/issues/28

**Comment by alphamu** [comment]
Probably because Google now by default includes only the Google maven repo and doesn't specify jcenter any more. In your <project root>/build.gradle make sure it says something like:
```
buildscript {
    repositories {
        jcenter()
        google()
    }
...
}
```

**Comment by alphamu** [comment]
Sorry, turns out there is no version `1.3.2` as you mentioned. I'll update the readme in the next round of updated.
