### ISSUE TITLE
Crash with AndroidX 1.0.0

### ISSUE THREAD

**Issue by gmk57** [alphamu/PinEntryEditText#45]
Hello & thanks for your work!
Latest versions (2.0.0-RC1 & 2.0.1-RC1), used with AndroidX 1.0.0, crash in runtime with:
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/legacy/view/ViewCompat;`
This class is [marked as deprecated](https://developer.android.com/reference/androidx/legacy/view/ViewCompat) and seems to be removed from AndroidX artifacts. Probably replacing `androidx.legacy.view.ViewCompat` with `androidx.core.view.ViewCompat` will resolve this issue.

**Comment by gmk57** [comment]
Version 2.0.1 still crashes.

**Comment by alphamu** [comment]
The app bundled with the library's source works. So, what are you doing differently? Or rather, are you suggesting that I use `androidx.core.view.ViewCompat` instead of the legacy one?

**Comment by alphamu** [comment]
If you're following the include instructions and excluding the legacy library.
Then you have to make sure to import it in your app.
The main reason to exclude the library when importing it into your project is to avoid version conflicts that can occur some times when the library uses a newer version of the included library than you do.
But, you need to make sure that if you exclude those androidx libraries, that you include them in your code. 
I'll do an other release soon where I switch to the `androidx.core.view.ViewCompat` and hopefully reduce one import.

**Comment by gmk57** [comment]
I had `appcompat` dependency, but not `support-v13` (never used it, honestly).
Also tried without excluding these artifacts, but it didn't help, since your library does not seem to have any transitive dependencies (see screenshot).
Switching to `androidx.core.view.ViewCompat` would be very nice, because `androidx.core:core` is already pulled by `appcompat`.
![screenshot](https://user-images.githubusercontent.com/22061463/46633735-3ebd8080-cb57-11e8-9e0d-02a2560df583.png)

**Comment by alphamu** [comment]
Removing ViewCompat doesn't seem to be working:
Checkout the branch `remove-viewcompat`
I still get an error that it can't find legacy ViewCompat.
any ideas?
```
ViewRootImpl$W@238bf91 does not exist
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8981)
        at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8972)
        at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2260)
        at com.android.server.wm.Session.remove(Session.java:193)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3286)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5878)
        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3619)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)```

**Comment by gmk57** [comment]
It seems that the crash is caused by using old published version of library in your sample project's build.gradle: `implementation ('com.alimuzaffar.lib:pinentryedittext:2.0.1')`
After reverting to `    implementation project(':pinentryedittext')` it works fine for me. :)

**Comment by alphamu** [comment]
AAAAAAAAAArg!
I've released `2.0.2` to bintray.
Please give it a try and let me know if this solves your problem.

**Comment by gmk57** [comment]
It works, thank you very much! :))

What do you intend to do with `appcompat` dependency? It seems that current artifact does not pull any transitive dependencies (see my screenshot above, this is still the case for 2.0.2).

I'm not an expert in libs publishing, but POM files for recent releases [do not contain](https://dl.bintray.com/alphamu/customwidgets/com/alimuzaffar/lib/pinentryedittext/2.0.2/pinentryedittext-2.0.2.pom) `<dependencies>` block. Last version that contained it was [1.3.1](https://dl.bintray.com/alphamu/customwidgets/com/alimuzaffar/lib/pinentryedittext/1.3.1/pinentryedittext-1.3.1.pom).

There are probably two choices:
1.  - Leave the code as is
    - Simplify examples in README to something like
`implementation 'com.alimuzaffar.lib:pinentryedittext:2.0.2'`
(as there is nothing to exclude)
    - Separately mention that project must define `appcompat` dependency itself.
2. - Dig out why dependencies get lost (publishing plugin bug?)
    - Consider simplifying examples in README to something like
`implementation 'com.alimuzaffar.lib:pinentryedittext:2.0.2'`
I'm not sure if excluding dependencies makes much sense. It's better to notice compatibility problems at compile time than at runtime, and with new [semantic versioning](https://android-developers.googleblog.com/2018/05/hello-world-androidx.html) there should be less false version conflicts.

**Comment by gmk57** [comment]
Version 1.3.3 released Feb 25, 2018 already did not have dependencies declared.
This may be related to `implementation` Gradle scope and [this issue](https://github.com/dcendents/android-maven-gradle-plugin/issues/61) in android-maven-gradle-plugin

**Comment by alphamu** [comment]
My tests showed that if I used `api` instead of `implementation` the dependencies become transitive... I could have read the documentation to learn the same thing :-P.
I've published a newer version of both widgets and the dependency should be transitive.
I've chosen to make the dependency transitive instead of asking the users to include appcompat because the widget will simply not work without this dependency so it should be transitive. The exclude then gives the user to option to use a newer version if they want.

**Comment by gmk57** [comment]
I still do not see transitive dependencies for 2.0.3 (neither in POM nor in Gradle dependencies report). :(
If [this issue](https://github.com/dcendents/android-maven-gradle-plugin/issues/61) is to blame, you may need to update android-maven-gradle-plugin.

**Comment by alphamu** [comment]
I'll take a look, but I don't create a POM.
I'm not sure what is happening, but the behaviour seems correct in the
sample app. clearly someone is happening when the library is bundled and
uploaded. I've synced it to maven, let me know if that made any difference,
otherwise I'll investigate this again.

**Comment by gmk57** [comment]
Sample app is in the same project with the library, so it may behave differently.

AFAIK, POM files are generated by android-maven-gradle-plugin (see `classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'` in your top-level `build.gradle`) and published on Bintray (here's [the latest](https://dl.bintray.com/alphamu/customwidgets/com/alimuzaffar/lib/pinentryedittext/2.0.3/pinentryedittext-2.0.3.pom)). They contain library metadata, including its transitive dependencies. There was indeed `<dependencies>` section in [version 1.3.1](https://dl.bintray.com/alphamu/customwidgets/com/alimuzaffar/lib/pinentryedittext/1.3.1/pinentryedittext-1.3.1.pom) (and earlier).

To verify you can:
1. Look at the published POM file, or
2. Create a new empty project, add 
`implementation 'com.alimuzaffar.lib:pinentryedittext:2.0.3'` to your `app\build.gradle` and 
run Gradle (in the top right corner) -> Project name -> :app -> Tasks -> help -> dependencies. 
You will see dependency tree.

**Comment by gmk57** [comment]
Glad to hear it! In v.2.0.4 there is indeed a transitive `appcompat` dependency. Thanks!
